### ISSUE TITLE
404 regarding addons links

### ISSUE THREAD

**Issue by InforMedic** [odoopbx/docs#2]
Wanted to let you know that the addons links here in the README and on https://docs.odoopbx.com/install/odoo.html leads to a 404. Seems the subfolder was removed. May you want to fix that links in the documentation =)

**Comment by litnimax** [comment]
Hello!
Thanks for your request.
The link to the addons will be removed from the docs as we do not distribute addons anymore from the github.
Now the addons are only available from the Odoo market.
